apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHN4eXl6ODZl
  CLOUDINARY_KEY: NDQ3NDE3OTQ1OTgzNzc0
  CLOUDINARY_SECRET: MFM0WlBFWDJ1Z1pjR3dyUEk5cnl5UDB0ZEJz
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lZV3RvYVd4dFpXVnpZV3hoSWl3aVlTSTZJbU50Y0hBMWVXSXpiVEF5TVRreWNuRjNOMjF6TTJSa2EzSWlmUS5rMk5ZSEc3R0p1NkZFbXNuUmsxcDhn
  DB_URL: bW9uZ29kYitzcnY6Ly9ha2hpbG1lZXNhbGEzNV9kYl91c2VyOjxkYl9wYXNzd29yZD5AYWtoaWx6LmtiM3NlaWYubW9uZ29kYi5uZXQvP2FwcE5hbWU9YWtoaWx6
