apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGRuMzluY2ky
  CLOUDINARY_KEY: MTE0NTgzNTMyMjY5MzU3
  CLOUDINARY_SECRET: UXpWemEwTTFZVVkyYlV4bWEweFhYM2hXWlhOVVpFOTZWRUpa
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lhMmx1WnpVMUlpd2lZU0k2SW1OdGNHbGxNbU5pYlRFNGVqa3ljM015YVdKNlp6WnNaR3NpZlEuaWhJbkd5Mi1pcElPTWpYQk4ya2dyZw==
  DB_URL: bW9uZ29kYitzcnY6Ly9zdW5ueWthdHRhNDVfZGJfdXNlcjo2SmFCMEVCVnkzWWFrZTV1QGFtaXQteWVscC5zN3dpeDg5Lm1vbmdvZGIubmV0Lz9hcHBOYW1lPUFtaXQteWVscA==